language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t isabellerichard/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true isabellerichard/multi-docker npm test

after_success:
  - docker build -t isabellerichard/multi-client ./client
  - docker build -t isabellerichard/multi-nginx ./nginx
  - docker build -t isabellerichard/multi-server ./server
  - docker build -t isabellerichard/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push isabellerichard/multi-client
  - docker push isabellerichard/multi-nginx
  - docker push isabellerichard/multi-server
  - docker push isabellerichard/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-265415978401"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY